development:
  adapter: postgresql
  encoding: unicode
  database: venuerific
  pool: 5
  username:
  password:
  host: localhost

<<<<<<< HEAD
test:
  adapter: postgresql
  encoding: unicode
  database: venuerific_test
  pool: 5
  username:
  password:
  host: localhost

=======
>>>>>>> ab0129e5817eced1dfd0a0051cd1c244399a0a61

production:
  url: <%= ENV['DATABASE_URL']%>