development:
  adapter: postgresql
  encoding: unicode
  database: venuerific
  pool: 5
  username:
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: venuerific_test
  pool: 5
  username:
  password:
  host: localhost

production:
  url: <%= ENV['DATABASE_URL']%>